WebMVC/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Services;

namespace WebMVC.Controllers
{
    public class CatalogController : Controller
    {

        private readonly IEventCatalogApiService _service;
        public CatalogController(IEventCatalogApiService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index(int? id)
        {
            var test = await _service.GetSingleEventAsync(id);

            return View(test);
        }


        [Authorize]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";


            return View();
        }
    }
}

WebMVC/Controllers/RandomEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models.Common;
using WebMVC.Services;
using WebMVC.ViewModels;

namespace WebMVC.Controllers
{
    public class RandomEventsController : Controller
    {
        private readonly IEventCatalogApiService _randomEvents;
        public RandomEventsController(IEventCatalogApiService randomEvent)
        {
            _randomEvents = randomEvent;
        }
        public async Task<IActionResult> Index(int? topicFilterApplied)
        {
           
            var events = await _randomEvents.GetRandomEventsAsync(topicFilterApplied);

            var tempRandomEvents = await _randomEvents.GetRandomEventsAsync(topicFilterApplied);

            var vm = new RandomEventsPageViewModel
            {

                HeaderEvent = tempRandomEvents.Data[0],
                CatalogEvents = events.Data,
                //Topic = await _randomEvents.GetTopicsAsync(),

                TopicFilterApplied = topicFilterApplied??0


            };
           // return View(vm);
            return View(vm);
        }
    }
}

WebMVC/Views/Catalog/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Authentication;
<h2>Access Token</h2>
<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>

    }
    <dt>access token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("access_token")</dd>
    <dt>refresh token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("refresh_token")</dd>
</dl>

WebMVC/Views/Catalog/Index.cshtml
 @model WebMVC.Models.Common.CatalogEvent

@{
    ViewData["Title"] = "Index";
}

<h1>@Html.DisplayFor(model => model.Title) </h1>

<div id="EventTitle" class="row"> 
    <div class="col-sm-1">
        
        <img class="esh-catalog-thumbnail" src="@Model.PictureUrl" width="600" height="360"/>

    </div>

<div>
    <hr />
    <h4>@Html.DisplayFor(model => model.Description)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.End)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenueName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenueAddressLine1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueAddressLine1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenueCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenueStateProvince)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueStateProvince)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenuePostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenuePostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VenueMapUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VenueMapUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HostOrganizer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HostOrganizer)
        </dd>
    </dl>
</div>
<div>
    <!--@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |-->
    <a asp-action="Index" asp-controller="RandomEvents">Back to Main Page</a>
</div>